-- Active: 1736771563614@@127.0.0.1@3306@photo_gallery
CREATE TABLE photos(
  id int AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  image_path varchar(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)